/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ldpc_toolbox
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LDPC_TOOLBOX_API_H
#define INCLUDED_LDPC_TOOLBOX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ldpc_toolbox_EXPORTS
#define LDPC_TOOLBOX_API __GR_ATTR_EXPORT
#else
#define LDPC_TOOLBOX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LDPC_TOOLBOX_API_H */
